### ISSUE TITLE
JSON decode error parsing `is_encryption_enabled`

### ISSUE THREAD

**Issue by jeffreyparker** [duosecurity/duo_universal_csharp#12]
When running the example app on my Mac (either using native dotnet for Mac, or docker), after completing the 2FA, I receive an internal server error:
```
An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot get the value of a token type 'True' as a string.
System.Text.Json.Utf8JsonReader.GetString()

JsonException: The JSON value could not be converted to System.String. Path: $.access_device.is_encryption_enabled | LineNumber: 0 | BytePositionInLine: 646.
```

Digging into the code and server's response, it seems this client is expecting a String value for `is_encryption_enabled`, but the server is returning the boolean true, causing the Deserialization error and exception.

This same issue also like affects `is_firewall_enabled` and `is_password_set`

Snippet of JSON from the server response:
```
"os":"Mac OS X","os_version":"12.3.1","browser":"Chrome","browser_version":"100.0.4896.75","flash_version":"uninstalled","java_version":"uninstalled","is_encryption_enabled":true,"is_firewall_enabled":true,"is_password_set":true},
```

**Comment by AaronAtDuo** [comment]
@tloveland1 and @devtendenz, I'd appreciate your input on this issue.  I see a few ways to address this:
A) Keep the field type 'string' and the possible values would be 'true', 'false', or 'unknown' - then it's the responsibility of anyone who cares about those fields to deal with the fact that this is effectively a string boolean
B) Change the field type to bool? so the possible values are true, false, or null
C) Leave the fields out entirely

Any ideas which would be most suitable for users of this client?

**Comment by AaronAtDuo** [comment]
D) make the field type object :yolo:

**Comment by AaronAtDuo** [comment]
Fixed by https://github.com/duosecurity/duo_universal_csharp/commit/c3e3b1293e5809d26c3a0c94af182c86c7d6ad01
