### ISSUE TITLE
Unable to run Sample 

### ISSUE THREAD

**Issue by rjankathi** [duosecurity/duo_universal_csharp#14]
Hi I am unable to run the sample here is the error i get, can somebody please help
{
  "error": "unauthorized_request",
  "error_description": "Unauthorized OIDC request"
}

**Comment by AaronAtDuo** [comment]
@rjankathi Were you able to get the example working with the above advice?

**Comment by rjankathi** [comment]
Thank you Aaron I was able to successfully run it. I missed using the Web SDK and figured it out but thanks for the advise which exactly what was needed.

**Comment by AaronAtDuo** [comment]
Glad you got it working.  Good luck and thanks for using Duo!
