### ISSUE TITLE
Add documentation on how to call from ASP.NET

### ISSUE THREAD

**Issue by JCervero** [duosecurity/duo_universal_csharp#15]
I spent a **lot** of time trying to figure out how to make the async calls work in our ASP.NET Web App. Can't make async calls without changing the pages and handlers to async but if you change the pages and handlers to async they can't write the to the session data. Other attempts to make the cal synchronously all resulted in deadlocks. The following works from the request thread without causing deadlocks:

`var token = Task.Run(async () =>
    {
        return await duoClient.ExchangeAuthorizationCodeFor2faResult(context.Request["code"], username);
    }).Result;`

Suggest adding it to the example and/or to the documentation.

**Comment by AaronAtDuo** [comment]
I agree this should be added to documentation.  Do you have any preference on where it should go?  I'm leaning toward a new README in the Example directory maybe?

**Comment by JCervero** [comment]
Seems reasonable to me.

**Comment by AaronAtDuo** [comment]
@JCervero How does https://github.com/duosecurity/duo_universal_csharp/blob/main/DuoUniversal.Example/README.md look?  Anything more you think should be included?
