### ISSUE TITLE
Microsoft.IdentityModel.JsonWebTokens Issue

### ISSUE THREAD

**Issue by m33p** [duosecurity/duo_universal_csharp#22]
It seems DuoUniversal has an issue with Microsoft.IdentityModel.JsonWebTokens 6.31.0 

I upgraded Microsoft.Graph in my project to 5.13.0 DuoUniversal began to fail with this error message.

ArgumentOutOfRangeException: IDX10720: Unable to create KeyedHashAlgorithm for algorithm 'HS512', the key size must be greater than: '512' bits, key has '320' bits. (Parameter 'keyBytes')

It seems to fail when issuing the DuoHealthCheck

**Comment by AaronAtDuo** [comment]
Just making some notes to myself...

Looks like the error is coming from https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/5068c6eaf1c87cf3fac7fb7411bbaee7ded8baa4/src/Microsoft.IdentityModel.Tokens/CryptoProviderFactory.cs#LL481C49-L481C49
basically, enforcing that HS512 keys are 64 bytes.  I wonder if this is a new enforcement....

**Comment by AaronAtDuo** [comment]
Yes, enforcement was added in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/008e2f7200685fb3fe8f98c7cd81e8971d2d8ed3 on May 8

**Comment by m33p** [comment]
Would this be a simple fix? I believe the Client Secret is as the key which seems not to be long enough. I can hold off on upgrading this package for the time being. I can see this issue becoming a bigger problem for people as time goes on.

**Comment by AaronAtDuo** [comment]
@m33p I don't have a fix to suggest right this moment.  You are correct that the key in question is the client secret provided by Duo.... unfortunately it's not a matter of simply providing a longer one, or encoding it differently so it consists of more bytes.  I definitely see this being a more and more common problem, and I'm discussing it with some internal teams.  I'll keep this issue posted with anything I find.

**Comment by m33p** [comment]
This is just a quick and dirty but appending the 44 zero bytes does appear to work in my initial testing. This could be written better I do get a successful result.

        private static SecurityKey GenerateSecurityKey(string secret)
        {
            byte[] keyBytes = Encoding.UTF8.GetBytes(secret);
            byte[] zeros = new byte[44] { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
                0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
                0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
                0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
                0x00, 0x00, 0x00, 0x00, 0x00 };
            keyBytes = keyBytes.Concat(zeros).ToArray();
            return new SymmetricSecurityKey(keyBytes);
        }

**Comment by AaronAtDuo** [comment]
I've put up a PR to fix this

**Comment by AaronAtDuo** [comment]
@m33p The PR is landed.  Is there any rush on a release to get this change out?  It'd be ideal to solve https://github.com/duosecurity/duo_universal_csharp/issues/24 before I do a release but if this can't wait, let me know.

**Comment by m33p** [comment]
@AaronAtDuo I think it can wait until issue #24 is resolved. There isn't a dire need for me to update the effected libraries at this point. I think I'm good if the release happens in the next month or two. Worse case if needed I can fork a copy and built it.

**Comment by AaronAtDuo** [comment]
@m33p Someone else ran into this, so I went ahead with the release; I'm still trying to fit in the error reporting work for a future release.
