### ISSUE TITLE
Duouniversal popup automatic login

### ISSUE THREAD

**Issue by Mastan12789** [duosecurity/duo_universal_csharp#30]
issue :
DuoUniversal popup directly redirect to our home page without entering otp or without access push notification.

may i know the reason ? 
Or do i need to do any settings in duo admin url to get the duo home page to select options?

**Comment by AaronAtDuo** [comment]
@Mastan12789 some of the most common reasons why a user might be able to get past Duo without having to authenticate:
- User or group is in 'bypass' status
- User selected "remember me" and thus has an existing Duo session
- Various policy settings such as trusted networks, new user policy, or trusted devices.

If you check the "Authentication Logs" in the Admin Panel for the Duo account you are testing with, that should provide information on why a user was allowed in.
