### ISSUE TITLE
IUserTwoFactorTokenProvider

### ISSUE THREAD

**Issue by mausch** [duosecurity/duo_universal_csharp#37]
We're currently implementing the "Traditional Prompt" and part of this is implementing [IUserTwoFactorTokenProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.iusertwofactortokenprovider-1?view=aspnetcore-8.0) for Duo.

How do we migrate this to the new "universal prompt"? There seems to be no mention of this anywhere.

Many thanks.

**Comment by mausch** [comment]
Yep sure, thanks. I guess since this is a .NET repo that has a example app I was expecting it to use the standard .NET APIs for 2FA integration. Or if the standard APIs are not to be used with the new Universal Prompt then why?

**Comment by AaronAtDuo** [comment]
@mausch The Duo prompt in general is not a "token" provider suitable for use with the built-in abstractions.  It is a web-based flow that involves redirecting the user out of the application and back.  While we do have a data object we refer to as a 'token' it is not the type of token that IUserTwoFactorTokenProvider deals with, as far as I can tell.

**Comment by mausch** [comment]
Thanks for the quick reply! 
It seems the developer that implemented this in our code used the wrong APIs then :slightly_smiling_face:

**Comment by AaronAtDuo** [comment]
Well, I can see how the old method (what we call "Web SDK 2") could be stretched to be considered a 'token', subject to special validation rules.  But I don't think the new scheme can unfortunately.
