### ISSUE TITLE
Reading certificates file broken on Windows

### ISSUE THREAD

**Issue by tloveland1** [duosecurity/duo_universal_csharp#4]
CertificatePinnerFactory::ReadCertsFromFile tries to split the contents of ca_certs.pem using Environment.NewLine. Windows uses CRLF line endings (the value of Environment.NewLine is "\r\n") but the .pem file uses LF line endings ("\n").

https://github.com/duosecurity/duo_universal_csharp/blob/4a8d878454d298917ed97b0c7cb10e883402523d/DuoUniversal/CertificatePinnerFactory.cs#L139-L140

This results in the certs being parsed improperly, and causes an AuthenticationException when trying to exchange the authorization code for the 2FA result.

Changing the line ending type of ca_certs.pem to CRLF from LF fixes the issue on Windows, but probably breaks on Linux. Alternatively, changing the value of twoNewLines to "\n\n" while keeping the line ending type of ca_certs.pem as LF also works.

Can you switch to splitting the new lines in a platform-neutral way? Maybe just split on a specific character(s) instead of new lines?

**Comment by AaronAtDuo** [comment]
The really confusing part is that devtendenz is having the opposite issue in https://github.com/duosecurity/duo_universal_csharp/issues/3.

I like your idea of moving away from line-ending based splitting, I'll see what I can do on that.

**Comment by AaronAtDuo** [comment]
@tloveland1 I think https://github.com/duosecurity/duo_universal_csharp/pull/6 will fix the issue, I'll try to get it merged as soon as I can get my team to review it.

**Comment by AaronAtDuo** [comment]
The PR is merged, let me know if it doesn't resolve your issue.

**Comment by tloveland1** [comment]
That worked, thanks!

**Comment by AaronAtDuo** [comment]
@tloveland1 Duo is interested in improving our developer experience, and if you are interested in providing us with feedback on that, please see below

Duo is looking to learn how to significantly improve the developer experience and what tools, resources, and technology (eg: sandboxes, new sdks, etc.) would best-enable customers to work faster and build things more easily with Duo's developer ecosystem. If your org is a Duo customer, and you have done development work (ex; authentication integrations, creation of a homegrown admin tool, log consumption for SIEMS, etc) with Duo's developer tools/resources in the past year, we would love to speak with you about your experience, what tools/resources you used, and your pain points.
This will be a 60-minute session during which you’ll have the opportunity to discuss your honest thoughts and feedback with Duo researchers. No preparation is necessary, and please know that this is not a sales call or product demo.
If you’re interested in participating, please email [lli@duosecurity.com](mailto:lli@duosecurity.com) to start the scheduling process.

Once the 60-minute session is complete, you will receive a token of appreciation in the form of a $75 e-gift card through Tremendous (options for Amazon or select retailers).

Please let me know if you have any questions!
Thanks!
